name: Continuous Integration

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Build Backend and Frontend
              run: |
                  cd backend
                  npm install
                  npm run build

                  cd ../frontend
                  npm install
                  npm run build

            - name: Create Dist and Public Folders
              run: |
                  mkdir build
                  mkdir build/dist
                  mkdir build/public
                  cp -r backend/dist/* build/dist/
                  cp -r frontend/dist/* build/public/
                  cp backend/package.json build/
                  cp dockerfile build/
                  cp .dockerignore build/

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: ./build
                  file: ./build/dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-manager:latest
